project_id = "tciosfzcxmtldeosawxq"

[functions.expire-pending-orders]
verify_jwt = false

[functions.normalize-products]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.verify-role]
verify_jwt = false

[functions.process-product-images]
verify_jwt = false

[functions.track-catalog-click]
verify_jwt = false
